### ISSUE TITLE
Where are the detailed installation instructions located?

### ISSUE THREAD

**Issue by fireheadman** [Icinga/icingaweb2-module-nagvis#16]
I can't for the life of me find a solid document that explains/shows how to install NagVis using this module.

The readme.md on the main page does not provide sufficient detail on how to get this going.   Your product would gain much more traction if it there were more details given.

Only thing I have found are many outdated blogs/write ups on how they like installing it... which only leads to issues if/when someone skips something.

**Comment by dnsmichi** [comment]
NagVis is a separate addon and thus needs to be installed on its own. It provides its own documentation.

Since you've already found some external sources which helped you out, can you help extend the documentation and send in a PR please?

**Comment by fireheadman** [comment]
I understand it is a separate addon.    however I am not finding the documentation to install it anywhere.     Perhaps I am assuming wrong to think this icinga sponsored branch is a good starting point?     Kinda of a catch-22 here.   You are asking me to help with documentation to install this module, yet I have no idea where to start.      

It looks like an interesting project, but maybe still a but new.   I consider myself new to this tool (coming from nagios).   I stick around on the sidelines for now and see how things progress.

Should you feel generous enough, feel free to update the main page for NagVis with some installation notes.

**Comment by c4ndies** [comment]
With this kind of reaction the issue shouldn't even be opened.

**Comment by fireheadman** [comment]
not sure what/who you are referring to.....

**Comment by Thomas-Gelf** [comment]
> I can't for the life of me find a solid document that explains/shows how to install NagVis using this module.

@fireheadman: as @dnsmichi already mentioned, this module doesn't care about installing NagVis. NagVis is a standalone software product and has it's own [documentation](http://docs.nagvis.org/1.8/en_US/index.html). This module is just the piece of glue that ties Icinga Web 2 and NagVis together.

> ...issues if/when someone skips something

Sure, I'm perfectly aware of similar problems. I always skip something and wonder afterwards why it didn't work out. Bought a table at Ikea. Didn't grasp that image showing the legs, therefore skipped that part. Didn't work out, so I had to complain. They told me their manager would call me back... still waiting...

Jokes apart, when our documentation isn't clear about the fact that an existing NagVis installation is a requirement, I consider this a bug. It's not our job to provide installation instructions for a third-party software. But we should probably make it more obvious that such a step is required.

Sure, it lists NagVis on top of the README file as one of it's two main requirements. And we thought that would suffice to get users started. This issue teaches me that **our assumption is wrong**. We usually have to deal with people perfectly being aware of what NagVis is. But not everybody who stumbles over this module has such a background.

Please correct me in case I'm wrong, but based on that conclusion I consider this a bug. Still, we'll not provide our own "How to install NagVis" guide. That's not our job. But we should fix this issue by a) clearly stating that such a step is required and b) pointing to the NagVis documentation helping one to get started.

> I understand it is a separate addon ... not finding the documentation

Well, that's the part that might irritate one or the other. I always had the impression that [NagVis](http://www.nagvis.org/) provided enough documentation and was easy to install. If that's not the case, shouldn't you complain [there](https://github.com/NagVis/nagvis/issues)? You don't blame the carport manufacturer for the fact that you couldn't figure out how to start your engine once you tried to park your car, do you?

Regards,
Thomas

**Comment by fireheadman** [comment]
@Thomas-Gelf 
excellent response Thomas!!!  <thumbs up from me>

Yes this clears the waters as I was not aware I needed to have nagvis first installed.   I assumed this was nagvis for icinga2/icingaweb2.

**Comment by Thomas-Gelf** [comment]
Glad I could help.
