### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by cbnorman** [Icinga/icingaweb2-module-nagvis#21]
can we drop the `backend = "ndomy_1"` from the documentation. it seems as though it will pickup the backend anyway and if your using icinga2 with psql your backend has to be live_1

**Comment by dgoetz** [comment]
I am against dropping it from the documentation as you typically want a default for your maps. And for Postgres: Nagvis 1.9 adds support for it instead of requiring livestatus.

**Comment by dnsmichi** [comment]
I haven't tested PostgreSQL support, but from my understanding the name of the configuration setting is "pgsql_1" following the underlaying naming schema. If this works out, the documentation should be updated to explain how to select a backend (if this is really needed).

**Comment by dgoetz** [comment]
Yes, postgres support is a new backendtype named pgsql, but backendname can be freely defined, also pgsql_1 will be perhaps default. Works fi

Adding to the document something like this in the "NagVis Configuration" section?

```
It is also required to configure your backend following the [Nagvis' Documentation](http://docs.nagvis.org/1.9/en_US/backends.html). Supported with Icinga 2 are the backendtypes ndomy, pgsql and mklivestatus. The setting `backend` in the defaults `section` should reflect your backend configuration.
```

**Comment by dnsmichi** [comment]
This has been partially added into #26.
