### ISSUE TITLE
NagVis webinterface shows "not authenticated"

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-nagvis#22]
With using the Icinga Web 2 authentication and the user is not logged in, the NagVis webinterface shows only "not authenticated". In my opinion it's better to have a redirect to the Icinga Web 2 loginpage instead.

**Comment by dnsmichi** [comment]
I tried to reproduce that with 1.9.2 and its seems that there is a fallback implemented if one auth provider does not work.

(I did not define any basic auth or similar).

![screen shot 2017-08-16 at 09 49 55](https://user-images.githubusercontent.com/382049/29352813-723d88bc-8268-11e7-99f7-e294be5777e8.png)

**Comment by dnsmichi** [comment]
Ah, my fault. The session is shared amongst browser tabs. The ugly text looks like this:

![screen shot 2017-08-16 at 09 53 45](https://user-images.githubusercontent.com/382049/29352930-d5202b2e-8268-11e7-922b-7ec38fd0e807.png)

**Comment by dnsmichi** [comment]
We could remove the die() section and let the redirect happen to /icingaweb2 (hardcoded). If we want to use base path of Icinga Web 2, we need to bootstrap a small webrouter (similar to how CSS/JS is served) and use that one. 

I'll think about it when I get more time, this exceeds the "5 minute look" ;)

**Comment by dnsmichi** [comment]
`icingaweb2/library/Icinga/Application/webrouter.php` <-> `icingaweb2-module-nagvis/library/nagvis-includes/CoreLogonIcingaweb2.php`

**Comment by cbnorman** [comment]
not sure what is meant by the last comment @dnsmichi ive recently updated icingaweb2 v2.5 and then i started to get the not authenticated message. im sure this is related to the pass through auth from icingaweb2. i have since updated to the latest nagvis 1.9.6 and it still seems to be happening when configuring the pass through auth.

**Comment by cbnorman** [comment]
another thing to note is im using centos 7.4 and had to enable rh-php71-php-fpm.service to be able to access icingaweb2 after the upgrade, im thinking this is affecting the pass-through authentication with nagvis, icingaweb2 itself seems to be operating fine?

**Comment by dnsmichi** [comment]
That's the location where the error is thrown, kept as a note if I ever look into this again. ATM I don't have time to do so.

**Comment by cbnorman** [comment]
i think my issue is slightly different im getting not authenticated when logged into icingaweb2. so since i upgraded im unable to login to nagvis at all. any idea why this could be and where i could look at logs?

**Comment by lippserd** [comment]
@cbnorman Please open a new issue for your case and provide all the necessary details, i.e. cookies, web2 and nagvis configuration, used versions, installation methods and the steps you've made in order to integrate nagvis into web2.

**Comment by cbnorman** [comment]
@lippserd created issue #28 hopefully that has enough info to work out my problem here
