### ISSUE TITLE
Errorpage with map restrictions

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-nagvis#23]
When nagvis/map/filter is set and the user opens one of those restricted maps an errorpage is shown (see screenshot). In my opinion it's better to hide those maps with restrictions from the menu.
<img width="1276" alt="bildschirmfoto 2017-07-13 um 21 32 01" src="https://user-images.githubusercontent.com/3973350/28186360-ca91f810-6812-11e7-9746-aeb14923f5d2.png">

**Comment by dnsmichi** [comment]
This has been added in #19 and 499f8337e740013674a68450773640ddc12616c4 already. Please ensure to use v1.1.1+ :)
