### ISSUE TITLE
Nagvis integration "nagvis/map/filter"

### ISSUE THREAD

**Issue by ivzquez** [Icinga/icingaweb2-module-nagvis#27]
Hi all,

I'm trying to limit the view of each user on my platform, so they can see only their own objects on Nagvis. I'm using the Nagvis integrated module for icingaweb2.

But, im not able to use the "nagvis/map/filter" on Roles configuration. I tried multiple filters.

How does it work?

![32547055-43a0fc36-c481-11e7-9c26-5b4c0a4b720e](https://user-images.githubusercontent.com/33484708/32559887-85254d0c-c4a8-11e7-87b2-1afc4d318095.png)

I have the only_permitted_objects directive enabled on nagvis.ini.php

Thanks

**Comment by lazyfrosch** [comment]
[Docs](https://github.com/Icinga/icingaweb2-module-nagvis/blob/6b56700f16182b780af28ede7a716965d735306e/doc/01-authorization.md#restrictions) say:

    Comma-separated set of case insensitive map name patterns (wildcard: *) a role is allowed to view

That should work.

Limiting data inside Nagvis is another issue.

`only_permitted_objects` is meant for the old contact authorization behavior. So your username needs to be a contact for host or service to be able to see it.

Does that help?
