### ISSUE TITLE
Maps restriction by regex generate an error clicking on the module link

### ISSUE THREAD

**Issue by ghost** [Icinga/icingaweb2-module-nagvis#30]
If you use the maps restriction by regex for a group of users, when a user that belongs to that group click on the map module, an error is shown: You're not allowed to view map "overview".
That's because if you don't specify a map, the default is picked up (overview map in this case).
But then there is a condition that check the name of the map with the restriction regex. If the restriction regex does not match the name of the default map (overview), it throws an exception. 

Here is the stacktrace:
#0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Nagvis\Controllers\ShowController->mapAction()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#6 {main}

I think that a possible solution is to get the list of the maps that can be reached also with the regex restriction and to show the first of them. If no maps are available, just show a page with a message on it, like: "You don't have access to the maps."

Steps to reproduce:
1. Create a limited maps usergroup by setting a valid regex (that not allows the default-map set in <ICINGAWEB_CONFIGDIR>/modules/nagvis/config.ini or the "demo-overview") in nagvis/map/filter text field.
2. Create a user with the limited maps usergroup.
3. Login with that user.
4. Access to map module.
5. The error is displayed and no other maps are reachable because the map menu is not shown.

Environment:
* Module version: 1.1.1 
* Icinga Web 2 version and modules: 2.5.1
* Icinga 2 version : 2.8.2
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache 2.4, PHP 7.1

**Comment by lippserd** [comment]
I don't know if this is still a problem, but I'm closing this as a wontfix.
