### ISSUE TITLE
Automap nagvis icingaweb2+director

### ISSUE THREAD

**Issue by Edekrusher** [Icinga/icingaweb2-module-nagvis#34]
Hello All! What kind of settings i must do for the right parent/child viewed in automap nagvis? 
I will creare field parents and make template_dependencyes and apply dependencyis... but nothing create in automap, all connect to one nagvis and no parent/child structure....

**Comment by dgoetz** [comment]
The automap requires the parent setting from Nagios which is not available in Icinga 2 as it does not provide this special dependency configuration.
