### ISSUE TITLE
Context Action Menu not Displaying

### ISSUE THREAD

**Issue by bmccorkle** [Icinga/icingaweb2-module-nagvis#37]
I'm unable to get actions on the context menu to display.   If I change over to local authentication for Nagvis, I can see them.  It seems like something isn't being handed over between the module and nagvis.   I have /nagvis/admin permissions set in IcingaWeb

## Expected Behavior
When right clicking on a host that has the proper tags set, I should see additional options in the context menu (exp:  Connect by SSH)

## Current Behavior
Nothing is displayed.  If I modify Nagvis to accept location authentication, I can see the additional context action items.  

http://docs.nagvis.org/1.9/en_US/extending/custom_context_actions.html

## Steps to Reproduce (for bugs)

1.  Edit nagvis.ini.php
2.  Enable needed Actions
[action_ssh_url]
action_type="ssh_url"
obj_type="host,service"
client_os="win,lnx,mac"
condition="TAGS~SSH"

3.  Assign custom variable 'TAGS' to host and set value to SSH
4. Right click on host  (Action item should be displayed but it isn't)

## Your Environment

* Module version (System - About): 1.1.1
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`):  2.10.3
* Operating System and version:  FreeBSD 11.2
* Webserver, PHP versions:  Apache 2.4.38 / PHP 7.3.3

**Comment by bmccorkle** [comment]
I've discovered a workaround.   In the nagvis context menu html file (default.context.html) if I change the lines as such:

"" lines to ""
"" lines to ""

I can see the action items.  It appears something isn't being exchanged properly for the permitted_perform macro.  Of course I think this means anyone with access will be able to see these actions.

https://monitoring.clarin.eu/nagvis/docs/en_US/context_templates.html

**Comment by bmccorkle** [comment]
My workaround doesn't seem to be perfect.   If the action is trying to call a custom file instead of URL it fails with the following:

{"message":"You are not permitted to access this page (Action\/perform\/).","title":"ERROR","type":"error"}

It works if I change Nagvis back to local authentication

**Comment by lippserd** [comment]
I'm sorry but we won't fix that.
