### ISSUE TITLE
Installation doc update

### ISSUE THREAD

**Issue by bitboy85** [Icinga/icingaweb2-module-nagvis#41]
Hi,
i've recently installed nagvis according to your given manual (very nice work!)

i noticed 2 things:
1. The nagvis installer copied its configuration only to /etc/apache2/conf-available
so i need to copy it to conf-enabled manually.

2. The file nagvis.ini.php has multiple lines with htmlcgi, one is in the section [backend_ndomy_1] this also needs to be changed.

Maybe you're willing to update your install doc.
Greets

**Comment by lippserd** [comment]
> 1. The nagvis installer copied its configuration only to /etc/apache2/conf-available
>    so i need to copy it to conf-enabled manually.

There are so many paths that would need to be adapted or generalized that I don't think it's worth the effort.

> 2\. The file nagvis.ini.php has multiple lines with htmlcgi, one is in the section [backend_ndomy_1] this also needs to be changed.

Our documentation says to set this globally:

```
[paths]
htmlcgi = "/icingaweb2"
```
