### ISSUE TITLE
Latest release seems old

### ISSUE THREAD

**Issue by LouGit** [Icinga/icingaweb2-module-nagvis#51]
## Expected Behavior

This is more of an organisational point of view, rather than technical.

In a project, we were using nagvis; but some people consider it as obsolete, because of the date of the latest release (Mar 14, 2017).
It's a pity, because the tool works fine, and it obviously seems to be actively maintained.

## Possible Solution

Would it be possible to make a release now, say a 1.1.2 version?

**Comment by LouGit** [comment]
A little up?

**Comment by yhabteab** [comment]
There will be a `1.2.0` release soon.
