### ISSUE TITLE
[dev.icinga.com #10858] URL is not always set correctly

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-nagvis#6]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10858

**Created by dgoetz on 2015-12-15 16:53:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-01 07:45:15 +00:00 (in Redmine)_

---

In some cases the map parameter is not correctly added to the URL while being on the default map and switching to another map. I recognized it while creating a new map and trying to toggle the menu to add icons. This will bring me back to the default map with menu shown instead of my newly created one.

**Comment by cbnorman** [comment]
I'm having this same issue so I can't create any new maps. Well I can create them but as soon as I use the drop down to select show nagvis menu it just takes me back to the default map. 

Does anyone have a fix for this?
