### ISSUE TITLE
[dev.icinga.com #10859] Filter is not working like expected

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-nagvis#7]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10859

**Created by dgoetz on 2015-12-15 16:58:03 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-01 07:45:04 +00:00 (in Redmine)_

---

I would expect the filter to be a comma separated list of maps (internal names), but this seems not to work at the moment or need also a specific permissions set. Can you have a look into it and add some hints to README or Moduleinfo?
It would also be helpful for the lazy admins to have some wildcard support.

**Comment by rajo** [comment]
Any plans when this could be fixed? Found this module and tried it - so far so good; but lacking a working filtering rule makes it unfortunately a bit unusable in a larger environment.

**Comment by rajo** [comment]
Thanks so far - the filtering itself is working, but ... :) 
icingaweb2 happily offers all configured maps in the menu - so users see probably a lot of "You're not allowed to view map XY" messages, until they reach the few maps they're allowed to view. In other words: icingaweb2 should honor the filter for the menu as well (as it is done with hostgroups e.g. -- here I'm also only offered those hostgroups which are allowed)

**Comment by dnsmichi** [comment]
Please open a new issue :-)

**Comment by lippserd** [comment]
Good point 👍
