### ISSUE TITLE
[dev.icinga.com #10934] Documentation

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-nagvis#8]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10934

**Created by kobmaki on 2016-01-05 20:48:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.1.0_
Last Update: _2016-02-01 07:45:40 +00:00 (in Redmine)_

---

Pull request for adding documentation section "doc/", to have a module documentation on the icingaweb2 gui. It is based on the README.md.

**Comment by dnsmichi** [comment]
For now I've left it intact inside the README.md file.
